import subprocess
import re
from .ats_engine import calculate_ats_score, extract_skills, generate_suggestions


def clean_lemma_output(raw):
    """Strip agent commentary/reasoning and any trailing duplicate chat-style
    answer that Lemma sometimes appends, keeping only the actual report."""
    if not raw:
        return raw

    # --- trim leading commentary: start at the report heading ---
    start_idx = raw.find("Resume Analysis")
    if start_idx == -1:
        m = re.search(r'(?m)^#{1,3}\s', raw)
        start_idx = m.start() if m else -1
    if start_idx != -1:
        raw = raw[start_idx:]

    # --- trim trailing commentary: cut after the report's own sign-off ---
    end_idx = -1
    for marker in ("Generated by ExamOS AI", "COMPLETED"):
        i = raw.find(marker)
        if i != -1:
            line_end = raw.find("\n", i)
            cut_at = line_end if line_end != -1 else len(raw)
            if end_idx == -1 or cut_at < end_idx:
                end_idx = cut_at
    if end_idx != -1:
        raw = raw[:end_idx]

    return raw.strip()


def analyze_text(text):

    try:
        # ==========================
        # DEBUGGING
        # ==========================
        print("TEXT LENGTH:", len(text))
        print(text[:200])

        # ==========================
        # CHECK IF PDF IS A RESUME
        # ==========================
        text_lower = text.lower()

        resume_keywords = [
            "education",
            "skills",
            "experience",
            "projects",
            "objective",
            "certifications"
        ]

        count = sum(1 for k in resume_keywords if k in text_lower)

        if count < 2:
            return {
                "status": "error",
                "message": "The uploaded PDF does not appear to be a resume."
            }

        # ==========================
        # RUN LEMMA
        # ==========================
        print("Starting Lemma...")

        result = subprocess.run(
            ["lemma", "agent", "run", "examos-agent", text],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=60
        )

        print("Lemma Finished")

        raw = result.stdout or ""
        raw = clean_lemma_output(raw)

        score = calculate_ats_score(text)
        found_skills, missing_skills = extract_skills(text)
        suggestions = generate_suggestions(found_skills, missing_skills, score)

        return {
            "status": "success",
            "ats_score": score,
            "skills": found_skills if found_skills else ["No matched skills found"],
            "missing_skills": missing_skills,
            "suggestions": suggestions,
            "analysis_raw": raw
        }

    except subprocess.TimeoutExpired:
        return {
            "status": "error",
            "message": "Lemma agent timed out (60s). Check if 'lemma' CLI is installed, logged in, and reachable."
        }
    except FileNotFoundError:
        return {
            "status": "error",
            "message": "'lemma' command not found. Make sure the Lemma CLI is installed and in PATH."
        }
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }